import mongoose from "mongoose";
import { connectDB, disconnectDB } from "../config/db";
import { Entity } from "../models/Entity";
import { Tag } from "../models/Tag";
import { TagRelation } from "../models/TagRelation";
import { TagService } from "../services/TagService";

const seedDatabase = async () => {
  console.log("🌱 Starting database seed...");
  await connectDB();

  // Clear existing collections
  await Entity.deleteMany({});
  await Tag.deleteMany({});
  await TagRelation.deleteMany({});

  console.log("🧹 Cleared existing data");

  // Create Entities
  const sources = await Entity.insertMany([
    { type: "source", content: "Understanding MongoDB Aggregation Framework", metadata: { author: "Alice" } },
    { type: "source", content: "PostgreSQL vs MongoDB: Which Database to choose?", metadata: { url: "https://example.com" } },
    { type: "source", content: "Getting started with TypeScript and Express", metadata: { score: 98 } },
  ]);

  const snippets = await Entity.insertMany([
    { type: "snippet", content: "db.collection.aggregate([{ $match: { status: 'A' } }])" },
    { type: "snippet", content: "SELECT * FROM users WHERE active = true;" },
    { type: "snippet", content: "app.use(express.json());" },
  ]);

  const aiResponses = await Entity.insertMany([
    { type: "ai_response", content: "MongoDB is a NoSQL database that stores data in JSON-like documents. It is highly scalable." },
    { type: "ai_response", content: "For strong ACID compliance and structured relational data, PostgreSQL is often preferred." },
    { type: "ai_response", content: "Node.js allows you to build scalable network applications using JavaScript." },
  ]);

  console.log("✅ Created pure entities");

  // Attach Tags using TagService to ensure internal logic (counts, dedupe) works properly
  console.log("🏷️ Attaching tags to entries...");

  // Source overlapping
  await TagService.attachTags(sources[0].id, "source", ["mongodb", "database", "nosql"]);
  await TagService.attachTags(sources[1].id, "source", ["mongodb", "database", "postgresql", "sql"]);
  await TagService.attachTags(sources[2].id, "source", ["typescript", "nodejs", "express", "backend"]);

  // Snippets overlapping
  await TagService.attachTags(snippets[0].id, "snippet", ["mongodb", "database", "aggregation"]);
  await TagService.attachTags(snippets[1].id, "snippet", ["postgresql", "database", "sql"]);
  await TagService.attachTags(snippets[2].id, "snippet", ["nodejs", "express", "backend"]);

  // AI Responses overlapping
  await TagService.attachTags(aiResponses[0].id, "ai_response", ["mongodb", "database", "nosql"]);
  await TagService.attachTags(aiResponses[1].id, "ai_response", ["postgresql", "database", "sql", "acid"]);
  await TagService.attachTags(aiResponses[2].id, "ai_response", ["nodejs", "backend", "javascript"]);

  console.log("✅ Tags attached successfully");

  // Tag usage count check
  const topTags = await Tag.find().sort({ usageCount: -1 }).limit(3);
  console.log("📊 Top 3 Tags generated by seed list:");
  topTags.forEach(t => console.log(`- ${t.name} (${t.usageCount} uses)`));

  await disconnectDB();
  console.log("🌱 Seed script finished successfully!");
};

seedDatabase().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
